version: '3'
services:

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    ports:
      - 9191:9191
    volumes:
      - ./ssl/:/etc/letsencrypt/
    command: certonly --standalone -d <cdn_host> -m <email> --no-eff-email --agree-tos
